---
language: ruby
dist: trusty
sudo: false
branches:
  only:
    - master
bundler_args: --without development system_tests
script:
    - bundle exec rake $CHECK
env:
    - CHECK=ci
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
