---
language: ruby
sudo: false
before_install: gem update --system
branches:
  only:
    - master
bundler_args: --without development system_tests
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1.9
  - 2.3.1
  - 2.4.0
notifications:
  email:
    - tim@bombasticmonkey.com
